drop table if exists Clients;
drop table if exists Comanda_Client;
drop table if exists Direccio;
drop table if exists Lot;
drop table if exists Peticions_Proveidor;
drop table if exists Producte;
drop table if exists Proveidors;
create table Clients (NIF integer not null, nom varchar(255), status tinyblob, primary key (NIF));
create table Comanda_Client (id integer not null, data_limit datetime, data_peticio datetime, estat tinyblob, ports integer, primary key (id));
create table Direccio (id integer not null, bloc integer, carrer varchar(255), codi_postal integer, latitud integer, longitud integer, pais varchar(255), poblacio varchar(255), primary key (id));
create table Lot (id integer not null, data_caducitat datetime, data_entrada datetime, stock integer, primary key (id));
create table Peticions_Proveidor (id integer not null, data_Ordre datetime, data_Recepcio datetime, estat tinyblob, quant_producte integer, tipus_peticio tinyblob, primary key (id));
create table Producte (id integer not null, descripcio_producte varchar(255), nom_producte varchar(255), preu integer, stock integer, stock_minim integer, tipus_producte tinyblob, unitat_mesura tinyblob, primary key (id));
create table Proveidors (CIFF integer not null, nom varchar(255), personaContacte varchar(255), status tinyblob, telefon varchar(255), tipus tinyblob, primary key (CIFF));
drop table if exists Clients;
drop table if exists Comanda_Client;
drop table if exists Direccio;
drop table if exists Lot;
drop table if exists Peticions_Proveidor;
drop table if exists Producte;
drop table if exists Proveidors;
create table Clients (NIF integer not null, nom varchar(255), status tinyblob, primary key (NIF));
create table Comanda_Client (id integer not null, data_limit datetime, data_peticio datetime, estat tinyblob, ports integer, primary key (id));
create table Direccio (id integer not null, bloc integer, carrer varchar(255), codi_postal integer, latitud integer, longitud integer, pais varchar(255), poblacio varchar(255), primary key (id));
create table Lot (id integer not null, data_caducitat datetime, data_entrada datetime, stock integer, primary key (id));
create table Peticions_Proveidor (id integer not null, data_Ordre datetime, data_Recepcio datetime, estat tinyblob, quant_producte integer, tipus_peticio tinyblob, primary key (id));
create table Producte (id integer not null, descripcio_producte varchar(255), nom_producte varchar(255), preu integer, stock integer, stock_minim integer, tipus_producte tinyblob, unitat_mesura tinyblob, primary key (id));
create table Proveidors (CIFF integer not null, nom varchar(255), personaContacte varchar(255), status tinyblob, telefon varchar(255), tipus tinyblob, primary key (CIFF));
