drop table if exists Clients CASCADE;
drop table if exists Comanda_Client CASCADE;
drop table if exists Direccio CASCADE;
drop table if exists Lot CASCADE;
drop table if exists Peticions_Proveidor CASCADE;
drop table if exists Producte CASCADE;
drop table if exists Proveidors CASCADE;
create table Clients (NIF integer not null, nom varchar(255), status tinyblob, primary key (NIF));
create table Comanda_Client (id integer not null, data_limit datetime, data_peticio datetime, estat tinyblob, ports integer, primary key (id));
create table Direccio (id integer not null, bloc integer, carrer varchar(255), codi_postal integer, latitud integer, longitud integer, pais varchar(255), poblacio varchar(255), primary key (id));
create table Lot (id integer not null, data_caducitat datetime, data_entrada datetime, stock integer, primary key (id));
create table Peticions_Proveidor (id integer not null, data_Ordre datetime, data_Recepcio datetime, estat tinyblob, quant_producte integer, tipus_peticio tinyblob, primary key (id));
create table Producte (id integer not null, descripcio_producte varchar(255), nom_producte varchar(255), preu integer, stock integer, stock_minim integer, tipus_producte tinyblob, unitat_mesura tinyblob, primary key (id));
create table Proveidors (CIFF integer not null, nom varchar(255), personaContacte varchar(255), status tinyblob, telefon varchar(255), tipus tinyblob, primary key (CIFF));
drop table if exists Clients;
drop table if exists Comanda_Client;
drop table if exists Direccio;
drop table if exists Lot;
drop table if exists Peticions_Proveidor;
drop table if exists Producte;
drop table if exists Proveidors;
create table Clients (NIF integer not null, nom varchar(255), status tinyblob, primary key (NIF));
create table Comanda_Client (id integer not null, data_limit datetime, data_peticio datetime, estat tinyblob, ports integer, primary key (id));
create table Direccio (id integer not null, bloc integer, carrer varchar(255), codi_postal integer, latitud integer, longitud integer, pais varchar(255), poblacio varchar(255), primary key (id));
create table Lot (id integer not null, data_caducitat datetime, data_entrada datetime, stock integer, primary key (id));
create table Peticions_Proveidor (id integer not null, data_Ordre datetime, data_Recepcio datetime, estat tinyblob, quant_producte integer, tipus_peticio tinyblob, primary key (id));
create table Producte (id integer not null, descripcio_producte varchar(255), nom_producte varchar(255), preu integer, stock integer, stock_minim integer, tipus_producte tinyblob, unitat_mesura tinyblob, primary key (id));
create table Proveidors (CIFF integer not null, nom varchar(255), personaContacte varchar(255), status tinyblob, telefon varchar(255), tipus tinyblob, primary key (CIFF));
alter table Clients drop foreign key FKkdly4xd343m4sflinwku546li;
alter table Comanda_Client drop foreign key FKcegfgf6vpn380be6iaipwgewv;
alter table composicio drop foreign key FK5275l6x7jhj8v6br8i93b23js;
alter table composicio drop foreign key FKqy0x5ue98ayoaohobsyvqrq6q;
alter table Direccio drop foreign key FK64sg5wqgsfkh58ptw0crrirsj;
alter table Direccio drop foreign key FKjrnwqs5yr0fytduh2s0i9un3j;
alter table Lot drop foreign key FKkxnsyrp7kqcalvptwjlxgwill;
alter table Peticions_Proveidor drop foreign key FKjuvubequua007yean2tx7jbqn;
alter table Peticions_Proveidor drop foreign key FKj5xe109bhba6xy3rrmbqkwjvw;
alter table ProducteComanda drop foreign key FKq3bimsr3fd63o4hgpydjwuubn;
alter table ProducteComanda drop foreign key FK11q4j316vcmm1ll8y2k85rgys;
alter table Proveidors drop foreign key FKfxr9h5tga1ynim4ydt7y5orcf;
drop table if exists Clients;
drop table if exists Comanda_Client;
drop table if exists composicio;
drop table if exists Direccio;
drop table if exists Lot;
drop table if exists Peticions_Proveidor;
drop table if exists Producte;
drop table if exists ProducteComanda;
drop table if exists Proveidors;
create table Clients (NIF integer not null, nom varchar(255), status tinyblob, Adreca integer not null, primary key (NIF));
create table Comanda_Client (id integer not null, data_limit date, data_peticio date, estat tinyblob, ports integer, comprador integer not null, primary key (id));
create table composicio (codiProducte integer not null, composicio_id integer not null, primary key (codiProducte, composicio_id));
create table Direccio (id integer not null, bloc integer, carrer varchar(255), codi_postal integer, latitud integer, longitud integer, pais varchar(255), poblacio varchar(255), client integer not null, partner integer not null, primary key (id));
create table Lot (id integer not null, data_caducitat date, data_entrada date, stock integer, producte integer, primary key (id));
create table Peticions_Proveidor (id integer not null, data_Ordre datetime, data_Recepcio datetime, estat tinyblob, quant_producte integer, tipus_peticio tinyblob, producte integer, proveidor integer, primary key (id));
create table Producte (id integer not null, descripcio_producte varchar(255), nom_producte varchar(255), preu integer, stock integer, stock_minim integer, tipus_producte tinyblob, unitat_mesura tinyblob, primary key (id));
create table ProducteComanda (id_Producte integer not null, id_comanda integer not null, primary key (id_producte, id_comanda));
create table Proveidors (idProveidor integer not null, CIFF integer, nom varchar(255), personaContacte varchar(255), status tinyblob, telefon varchar(255), tipus tinyblob, address integer not null, primary key (idProveidor));
alter table Clients add constraint FKkdly4xd343m4sflinwku546li foreign key (Adreca) references Direccio (id);
alter table Comanda_Client add constraint FKcegfgf6vpn380be6iaipwgewv foreign key (comprador) references Clients (NIF);
alter table composicio add constraint FK5275l6x7jhj8v6br8i93b23js foreign key (composicio_id) references Producte (id);
alter table composicio add constraint FKqy0x5ue98ayoaohobsyvqrq6q foreign key (codiProducte) references Producte (id);
alter table Direccio add constraint FK64sg5wqgsfkh58ptw0crrirsj foreign key (client) references Clients (NIF);
alter table Direccio add constraint FKjrnwqs5yr0fytduh2s0i9un3j foreign key (partner) references Proveidors (idProveidor);
alter table Lot add constraint FKkxnsyrp7kqcalvptwjlxgwill foreign key (producte) references Producte (id);
alter table Peticions_Proveidor add constraint FKjuvubequua007yean2tx7jbqn foreign key (producte) references Producte (id);
alter table Peticions_Proveidor add constraint FKj5xe109bhba6xy3rrmbqkwjvw foreign key (proveidor) references Proveidors (idProveidor);
alter table ProducteComanda add constraint FKq3bimsr3fd63o4hgpydjwuubn foreign key (id_comanda) references Producte (id);
alter table ProducteComanda add constraint FK11q4j316vcmm1ll8y2k85rgys foreign key (id_Producte) references Producte (id);
alter table Proveidors add constraint FKfxr9h5tga1ynim4ydt7y5orcf foreign key (address) references Direccio (id);
alter table Clients drop foreign key FKkdly4xd343m4sflinwku546li;
alter table Comanda_Client drop foreign key FKcegfgf6vpn380be6iaipwgewv;
alter table composicio drop foreign key FK5275l6x7jhj8v6br8i93b23js;
alter table composicio drop foreign key FKqy0x5ue98ayoaohobsyvqrq6q;
alter table Direccio drop foreign key FK64sg5wqgsfkh58ptw0crrirsj;
alter table Direccio drop foreign key FKjrnwqs5yr0fytduh2s0i9un3j;
alter table Lot drop foreign key FKkxnsyrp7kqcalvptwjlxgwill;
alter table Peticions_Proveidor drop foreign key FKjuvubequua007yean2tx7jbqn;
alter table Peticions_Proveidor drop foreign key FKj5xe109bhba6xy3rrmbqkwjvw;
alter table ProducteComanda drop foreign key FKq3bimsr3fd63o4hgpydjwuubn;
alter table ProducteComanda drop foreign key FK11q4j316vcmm1ll8y2k85rgys;
alter table Proveidors drop foreign key FKfxr9h5tga1ynim4ydt7y5orcf;
drop table if exists Clients;
drop table if exists Comanda_Client;
drop table if exists composicio;
drop table if exists Direccio;
drop table if exists Lot;
drop table if exists Peticions_Proveidor;
drop table if exists Producte;
drop table if exists ProducteComanda;
drop table if exists Proveidors;
create table Clients (NIF varchar(255) not null, nom varchar(255), status bit, Adreca integer not null, primary key (NIF));
create table Comanda_Client (id integer not null, data_limit date, data_peticio date, estat integer, ports integer, comprador varchar(255) not null, primary key (id));
create table composicio (codiProducte integer not null, composicio_id integer not null, primary key (codiProducte, composicio_id));
create table Direccio (id integer not null, bloc integer, carrer varchar(255), codi_postal integer, latitud integer, longitud integer, pais varchar(255), poblacio varchar(255), client varchar(255) not null, partner integer not null, primary key (id));
create table Lot (id integer not null, data_caducitat date, data_entrada date, stock integer, producte integer, primary key (id));
create table Peticions_Proveidor (id integer not null, data_Ordre datetime, data_Recepcio datetime, estat tinyblob, quant_producte integer, tipus_peticio tinyblob, producte integer, proveidor integer, primary key (id));
create table Producte (id integer not null, descripcio_producte varchar(255), nom_producte varchar(255), preu double precision, stock integer, stock_minim integer, tipus_producte tinyblob, unitat_mesura tinyblob, primary key (id));
create table ProducteComanda (id_Producte integer not null, id_comanda integer not null, primary key (id_producte, id_comanda));
create table Proveidors (idProveidor integer not null, CIFF integer, nom varchar(255), personaContacte varchar(255), status tinyblob, telefon varchar(255), tipus tinyblob, address integer not null, primary key (idProveidor));
alter table Clients add constraint FKkdly4xd343m4sflinwku546li foreign key (Adreca) references Direccio (id);
alter table Comanda_Client add constraint FKcegfgf6vpn380be6iaipwgewv foreign key (comprador) references Clients (NIF);
alter table composicio add constraint FK5275l6x7jhj8v6br8i93b23js foreign key (composicio_id) references Producte (id);
alter table composicio add constraint FKqy0x5ue98ayoaohobsyvqrq6q foreign key (codiProducte) references Producte (id);
alter table Direccio add constraint FK64sg5wqgsfkh58ptw0crrirsj foreign key (client) references Clients (NIF);
alter table Direccio add constraint FKjrnwqs5yr0fytduh2s0i9un3j foreign key (partner) references Proveidors (idProveidor);
alter table Lot add constraint FKkxnsyrp7kqcalvptwjlxgwill foreign key (producte) references Producte (id);
alter table Peticions_Proveidor add constraint FKjuvubequua007yean2tx7jbqn foreign key (producte) references Producte (id);
alter table Peticions_Proveidor add constraint FKj5xe109bhba6xy3rrmbqkwjvw foreign key (proveidor) references Proveidors (idProveidor);
alter table ProducteComanda add constraint FKq3bimsr3fd63o4hgpydjwuubn foreign key (id_comanda) references Producte (id);
alter table ProducteComanda add constraint FK11q4j316vcmm1ll8y2k85rgys foreign key (id_Producte) references Producte (id);
alter table Proveidors add constraint FKfxr9h5tga1ynim4ydt7y5orcf foreign key (address) references Direccio (id);
